### ISSUE TITLE
Some images not loading properly

### ISSUE THREAD

**Issue by anoda9** [zmj/MTG-Draft-Viewer#1]
I don't have twitter, so I figured I could contact you here. Sometimes images don't load in the draft viewer - it usually involves cards with "AE" or punctuation in the name. (AEther Web; Ith, High Arcanist). See this draft for examples: (pick 1.4)
http://www.empirimancy.net/draft/6994153

Aside from this bug, your site is amazing - definitely the best draft converter I've found so far. 
Out of curiosity, how long are the drafts saved on the server/site once they are uploaded?

**Comment by zmj** [comment]
Thanks for the feedback. I thought I was getting most of the weird characters, but it looks like I'm missing a few, and commas aren't being caught at all. It's a bit of a guessing game exactly how Wizards will format the card URLs on their site - I'm not actually hosting the images myself.

Right now I don't have any plans to expire draft logs until I start hitting capacity limits on my linode machine. I have some vague intentions to move the service to a new domain where the drafts can be viewed by user, and import all the existing drafts logs to that.

**Comment by zmj** [comment]
This should be fixed now. Version control misuse on the server hosting the app.
